version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/bridge"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Kyiv"
    open-pull-requests-limit: 5
    groups:
      go-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/ha-cards"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Kyiv"
    open-pull-requests-limit: 5
    groups:
      ha-cards-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/new-ha-cards"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Kyiv"
    open-pull-requests-limit: 5
    groups:
      new-ha-cards-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/bridge"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Kyiv"
    open-pull-requests-limit: 5
    groups:
      docker-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Kyiv"
    open-pull-requests-limit: 5
    groups:
      actions-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
