package hamqtt

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"maps"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/RCooLeR/jinko-exporter/bridge/internal/config"
	"github.com/RCooLeR/jinko-exporter/bridge/internal/model"
)

const (
	discoveryStateVersion       = 1
	maxDiscoveryStateBytes      = 1 << 20
	maxDiscoveryStateMetrics    = 4096
	maxDiscoveryStateSources    = 64
	maxDiscoveryStateMetaKeys   = 512
	maxDiscoveryStateJSONDepth  = 32
	maxDiscoveryStateShortText  = 256
	maxDiscoveryStateMetricName = 1024
	maxDiscoveryStateTopic      = 2048
)

// discoveryState stores typed entity ownership, not MQTT discovery payloads.
// Payloads are regenerated by the current binary after every load so template
// and security fixes are applied to entities learned by older releases.
type discoveryState struct {
	Version         int                                         `json:"version"`
	Binding         discoveryStateBinding                       `json:"binding"`
	OrdinaryMetrics map[string]discoveryMetricSchema            `json:"ordinary_metrics"`
	GridLoadMetrics map[string]discoveryMetricSchema            `json:"grid_load_metrics"`
	AlertMetrics    map[string]map[string]discoveryMetricSchema `json:"alert_metrics"`
	PrimaryMetaKeys []string                                    `json:"primary_meta_keys"`
}

type discoveryStateBinding struct {
	TopicPrefix       string `json:"topic_prefix"`
	DiscoveryPrefix   string `json:"discovery_prefix"`
	DeviceID          string `json:"device_id"`
	DeviceIdentifier  string `json:"device_identifier"`
	StateTopic        string `json:"state_topic"`
	AvailabilityTopic string `json:"availability_topic"`
	PrimarySource     string `json:"primary_source"`
}

type discoveryMetricSchema struct {
	Group string `json:"group"`
	Key   string `json:"key"`
	Name  string `json:"name"`
	Unit  string `json:"unit,omitempty"`
}

func newDiscoveryState(binding discoveryStateBinding) discoveryState {
	return discoveryState{
		Version:         discoveryStateVersion,
		Binding:         binding,
		OrdinaryMetrics: make(map[string]discoveryMetricSchema),
		GridLoadMetrics: make(map[string]discoveryMetricSchema),
		AlertMetrics:    make(map[string]map[string]discoveryMetricSchema),
		PrimaryMetaKeys: make([]string, 0),
	}
}

func normalizeSourceName(value string) string {
	return strings.ToLower(strings.TrimSpace(value))
}

func metricSchema(metric model.Metric) discoveryMetricSchema {
	return discoveryMetricSchema{
		Group: strings.TrimSpace(metric.Group),
		Key:   strings.TrimSpace(metric.Key),
		Name:  strings.TrimSpace(metric.Name),
		Unit:  strings.TrimSpace(metric.Unit),
	}
}

func (schema discoveryMetricSchema) metric() model.Metric {
	return model.Metric{
		Group: schema.Group,
		Key:   schema.Key,
		Name:  schema.Name,
		Unit:  schema.Unit,
	}
}

func (state discoveryState) clone() discoveryState {
	cloned := discoveryState{
		Version:         state.Version,
		Binding:         state.Binding,
		OrdinaryMetrics: cloneMetricSchemas(state.OrdinaryMetrics),
		GridLoadMetrics: cloneMetricSchemas(state.GridLoadMetrics),
		AlertMetrics:    make(map[string]map[string]discoveryMetricSchema, len(state.AlertMetrics)),
		PrimaryMetaKeys: make([]string, len(state.PrimaryMetaKeys)),
	}
	copy(cloned.PrimaryMetaKeys, state.PrimaryMetaKeys)
	for source, metrics := range state.AlertMetrics {
		cloned.AlertMetrics[source] = cloneMetricSchemas(metrics)
	}
	return cloned
}

func cloneMetricSchemas(source map[string]discoveryMetricSchema) map[string]discoveryMetricSchema {
	cloned := make(map[string]discoveryMetricSchema, len(source))
	maps.Copy(cloned, source)
	return cloned
}

func (state *discoveryState) mergeSnapshot(snapshot *model.Snapshot, primarySource string) (bool, error) {
	if snapshot == nil {
		return false, nil
	}
	source := normalizeSourceName(snapshot.Source)
	changed := false
	for _, metric := range snapshot.Metrics {
		stateKey := metricStateKey(metric)
		if stateKey == "" {
			continue
		}
		schema := metricSchema(metric)
		var target map[string]discoveryMetricSchema
		category := ""
		switch {
		case isAlertMetric(metric):
			alertSource := source
			if alertSource == "" {
				alertSource = "unknown_source"
			}
			target = state.AlertMetrics[alertSource]
			if target == nil {
				target = make(map[string]discoveryMetricSchema)
				state.AlertMetrics[alertSource] = target
			}
			category = "alert source " + alertSource
		case strings.EqualFold(strings.TrimSpace(metric.Group), "grid_load"):
			target = state.GridLoadMetrics
			category = "grid_load"
		case source == primarySource:
			target = state.OrdinaryMetrics
			category = "ordinary primary-source"
		default:
			// A cold fallback is allowed to publish health/identity and its own
			// alert domain, but cannot establish ordinary HA entity ownership.
			// If it uses an already-owned canonical key, require the same typed
			// schema before allowing its value into that entity's state.
			if existing, owned := state.OrdinaryMetrics[stateKey]; owned && existing != schema {
				return false, fmt.Errorf("MQTT discovery fallback metric %q conflicts with its primary-source schema", stateKey)
			}
			continue
		}
		added, err := mergeMetricSchema(target, stateKey, schema, category)
		if err != nil {
			return false, err
		}
		changed = changed || added
	}

	if source == primarySource {
		known := make(map[string]struct{}, len(state.PrimaryMetaKeys)+len(snapshot.Meta))
		for _, key := range state.PrimaryMetaKeys {
			known[key] = struct{}{}
		}
		for key := range snapshot.Meta {
			stateKey := sanitizeID(key)
			if stateKey == "" {
				continue
			}
			if _, exists := known[stateKey]; exists {
				continue
			}
			known[stateKey] = struct{}{}
			state.PrimaryMetaKeys = append(state.PrimaryMetaKeys, stateKey)
			changed = true
		}
		if changed {
			sort.Strings(state.PrimaryMetaKeys)
		}
	}

	return changed, nil
}

func mergeMetricSchema(target map[string]discoveryMetricSchema, stateKey string, schema discoveryMetricSchema, category string) (bool, error) {
	if existing, ok := target[stateKey]; ok {
		if existing != schema {
			return false, fmt.Errorf("MQTT discovery %s metric %q changed schema", category, stateKey)
		}
		return false, nil
	}
	target[stateKey] = schema
	return true, nil
}

func (state discoveryState) allMetrics() ([]model.Metric, error) {
	byKey := make(map[string]discoveryMetricSchema)
	add := func(category string, schemas map[string]discoveryMetricSchema) error {
		for stateKey, schema := range schemas {
			if existing, ok := byKey[stateKey]; ok {
				if existing != schema {
					return fmt.Errorf("MQTT discovery metric %q has conflicting schemas across %s", stateKey, category)
				}
				continue
			}
			byKey[stateKey] = schema
		}
		return nil
	}
	if err := add("ordinary and grid_load categories", state.OrdinaryMetrics); err != nil {
		return nil, err
	}
	if err := add("ordinary and grid_load categories", state.GridLoadMetrics); err != nil {
		return nil, err
	}
	sources := sortedKeys(state.AlertMetrics)
	for _, source := range sources {
		if err := add("alert source "+source, state.AlertMetrics[source]); err != nil {
			return nil, err
		}
	}
	keys := sortedKeys(byKey)
	metrics := make([]model.Metric, 0, len(keys))
	for _, key := range keys {
		metrics = append(metrics, byKey[key].metric())
	}
	return metrics, nil
}

func (state discoveryState) alertSources() []string {
	return sortedKeys(state.AlertMetrics)
}

// alertMetricDomains preserves the source ownership that allMetrics necessarily
// flattens for Home Assistant entity generation. A shared state key is safe only
// when every source gives it the exact same typed meaning; in that case one
// entity can be available for any of those explicitly recorded alert domains.
func (state discoveryState) alertMetricDomains() (map[string][]string, error) {
	domainsByKey := make(map[string][]string)
	schemaByKey := make(map[string]discoveryMetricSchema)
	for _, source := range state.alertSources() {
		domain := alertDomain(source)
		for stateKey, schema := range state.AlertMetrics[source] {
			if existing, ok := schemaByKey[stateKey]; ok && existing != schema {
				return nil, fmt.Errorf("MQTT discovery alert metric %q has ambiguous semantics across source domains", stateKey)
			}
			schemaByKey[stateKey] = schema
			domainsByKey[stateKey] = append(domainsByKey[stateKey], domain)
		}
	}
	for stateKey := range domainsByKey {
		sort.Strings(domainsByKey[stateKey])
	}
	return domainsByKey, nil
}

func sortedKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func loadDiscoveryState(path string, expected discoveryStateBinding) (discoveryState, bool, error) {
	file, err := os.Open(path)
	if errors.Is(err, os.ErrNotExist) {
		state := newDiscoveryState(expected)
		if err := validateDiscoveryState(state, expected); err != nil {
			return discoveryState{}, false, err
		}
		return state, false, nil
	}
	if err != nil {
		return discoveryState{}, false, fmt.Errorf("open MQTT discovery state: %w", err)
	}
	defer func() { _ = file.Close() }()

	raw, err := io.ReadAll(io.LimitReader(file, maxDiscoveryStateBytes+1))
	if err != nil {
		return discoveryState{}, false, fmt.Errorf("read MQTT discovery state: %w", err)
	}
	if len(raw) > maxDiscoveryStateBytes {
		return discoveryState{}, false, fmt.Errorf("MQTT discovery state exceeds %d bytes", maxDiscoveryStateBytes)
	}
	if err := rejectDuplicateJSONKeys(raw); err != nil {
		return discoveryState{}, false, fmt.Errorf("decode MQTT discovery state: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	var state discoveryState
	if err := decoder.Decode(&state); err != nil {
		return discoveryState{}, false, fmt.Errorf("decode MQTT discovery state: %w", err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		if err == nil {
			return discoveryState{}, false, errors.New("decode MQTT discovery state: multiple JSON values")
		}
		return discoveryState{}, false, fmt.Errorf("decode MQTT discovery state trailing data: %w", err)
	}
	if err := validateDiscoveryState(state, expected); err != nil {
		return discoveryState{}, false, err
	}
	return state, true, nil
}

func rejectDuplicateJSONKeys(raw []byte) error {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	var walkValue func(int) error
	walkValue = func(depth int) error {
		if depth > maxDiscoveryStateJSONDepth {
			return fmt.Errorf("JSON nesting exceeds %d levels", maxDiscoveryStateJSONDepth)
		}
		token, err := decoder.Token()
		if err != nil {
			return err
		}
		delim, compound := token.(json.Delim)
		if !compound {
			return nil
		}
		switch delim {
		case '{':
			seen := make(map[string]struct{})
			for decoder.More() {
				keyToken, err := decoder.Token()
				if err != nil {
					return err
				}
				key, ok := keyToken.(string)
				if !ok {
					return errors.New("JSON object key is not a string")
				}
				if _, duplicate := seen[key]; duplicate {
					return fmt.Errorf("duplicate JSON object key %q", key)
				}
				seen[key] = struct{}{}
				if err := walkValue(depth + 1); err != nil {
					return err
				}
			}
			end, err := decoder.Token()
			if err != nil {
				return err
			}
			if end != json.Delim('}') {
				return errors.New("invalid JSON object terminator")
			}
		case '[':
			for decoder.More() {
				if err := walkValue(depth + 1); err != nil {
					return err
				}
			}
			end, err := decoder.Token()
			if err != nil {
				return err
			}
			if end != json.Delim(']') {
				return errors.New("invalid JSON array terminator")
			}
		default:
			return fmt.Errorf("unexpected JSON delimiter %q", delim)
		}
		return nil
	}
	return walkValue(0)
}

func persistDiscoveryState(path string, state discoveryState) error {
	if err := validateDiscoveryState(state, state.Binding); err != nil {
		return err
	}

	var raw bytes.Buffer
	encoder := json.NewEncoder(&raw)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(state); err != nil {
		return fmt.Errorf("encode MQTT discovery state: %w", err)
	}
	if raw.Len() > maxDiscoveryStateBytes {
		return fmt.Errorf("MQTT discovery state exceeds %d bytes", maxDiscoveryStateBytes)
	}

	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".jinko-mqtt-discovery-state-*")
	if err != nil {
		return fmt.Errorf("create temporary MQTT discovery state: %w", err)
	}
	tmpName := tmp.Name()
	removeTemp := true
	defer func() {
		_ = tmp.Close()
		if removeTemp {
			_ = os.Remove(tmpName)
		}
	}()

	if err := tmp.Chmod(0o600); err != nil {
		return fmt.Errorf("secure temporary MQTT discovery state: %w", err)
	}
	if _, err := tmp.Write(raw.Bytes()); err != nil {
		return fmt.Errorf("write temporary MQTT discovery state: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		return fmt.Errorf("sync temporary MQTT discovery state: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temporary MQTT discovery state: %w", err)
	}
	if err := replaceDiscoveryStateFile(tmpName, path); err != nil {
		return fmt.Errorf("replace MQTT discovery state: %w", err)
	}
	removeTemp = false
	if err := syncDiscoveryStateLocation(path); err != nil {
		return fmt.Errorf("sync MQTT discovery state location: %w", err)
	}
	return nil
}

func validateDiscoveryState(state discoveryState, expected discoveryStateBinding) error {
	if state.Version != discoveryStateVersion {
		return fmt.Errorf("MQTT discovery state version %d is unsupported; want %d", state.Version, discoveryStateVersion)
	}
	if state.Binding != expected {
		return errors.New("MQTT discovery state ownership binding does not match the configured publisher")
	}
	if err := validateDiscoveryBinding(state.Binding); err != nil {
		return err
	}
	if state.OrdinaryMetrics == nil || state.GridLoadMetrics == nil || state.AlertMetrics == nil || state.PrimaryMetaKeys == nil {
		return errors.New("MQTT discovery state schema collections must be JSON arrays/objects, not null")
	}
	if len(state.AlertMetrics) > maxDiscoveryStateSources {
		return fmt.Errorf("MQTT discovery state has more than %d alert sources", maxDiscoveryStateSources)
	}
	if len(state.PrimaryMetaKeys) > maxDiscoveryStateMetaKeys {
		return fmt.Errorf("MQTT discovery state has more than %d primary metadata keys", maxDiscoveryStateMetaKeys)
	}

	totalMetrics := len(state.OrdinaryMetrics) + len(state.GridLoadMetrics)
	if err := validateMetricSchemas("ordinary", state.OrdinaryMetrics, func(metric model.Metric) bool {
		return !isAlertMetric(metric) && !strings.EqualFold(strings.TrimSpace(metric.Group), "grid_load")
	}); err != nil {
		return err
	}
	if err := validateMetricSchemas("grid_load", state.GridLoadMetrics, func(metric model.Metric) bool {
		return !isAlertMetric(metric) && strings.EqualFold(strings.TrimSpace(metric.Group), "grid_load")
	}); err != nil {
		return err
	}

	domains := make(map[string]string, len(state.AlertMetrics))
	for source, metrics := range state.AlertMetrics {
		if source == "" || source != normalizeSourceName(source) || len(source) > maxDiscoveryStateShortText {
			return fmt.Errorf("MQTT discovery state alert source %q is not normalized or is too long", source)
		}
		if len(metrics) == 0 {
			return fmt.Errorf("MQTT discovery state alert source %q has no metric schema", source)
		}
		domain := alertDomain(source)
		if previous, duplicate := domains[domain]; duplicate && previous != source {
			return fmt.Errorf("MQTT discovery alert sources %q and %q collide after topic normalization", previous, source)
		}
		domains[domain] = source
		if err := validateMetricSchemas("alert source "+source, metrics, isAlertMetric); err != nil {
			return err
		}
		totalMetrics += len(metrics)
	}
	if totalMetrics > maxDiscoveryStateMetrics {
		return fmt.Errorf("MQTT discovery state has more than %d metric schemas", maxDiscoveryStateMetrics)
	}
	if _, err := state.allMetrics(); err != nil {
		return err
	}
	if _, err := state.alertMetricDomains(); err != nil {
		return err
	}

	previous := ""
	for _, key := range state.PrimaryMetaKeys {
		if key == "" || key != sanitizeID(key) || len(key) > maxDiscoveryStateShortText {
			return fmt.Errorf("MQTT discovery state metadata key %q is not normalized or is too long", key)
		}
		if previous != "" && key <= previous {
			return errors.New("MQTT discovery state metadata keys must be strictly sorted and unique")
		}
		previous = key
	}
	if err := validateDiscoveryTopicNamespace(state); err != nil {
		return err
	}
	return nil
}

func validateDiscoveryTopicNamespace(state discoveryState) error {
	seen := make(map[string]string)
	add := func(component, suffix, owner string) error {
		key := component + "/" + sanitizeID(suffix)
		if previous, duplicate := seen[key]; duplicate {
			return fmt.Errorf("MQTT discovery topic suffix %q is owned by both %s and %s", key, previous, owner)
		}
		seen[key] = owner
		return nil
	}
	for _, entity := range diagnosticEntities {
		if err := add("sensor", entity.StateKey, "diagnostic "+entity.StateKey); err != nil {
			return err
		}
	}
	for _, key := range state.PrimaryMetaKeys {
		if err := add("sensor", "meta_"+key, "primary metadata "+key); err != nil {
			return err
		}
	}
	if err := add("binary_sensor", "poll_up", "poll connectivity"); err != nil {
		return err
	}
	if err := add("binary_sensor", "alarm_or_fault_active", "exact legacy aggregate tombstone"); err != nil {
		return err
	}
	for _, source := range state.alertSources() {
		if err := add("binary_sensor", alertDomain(source)+"_warning_alarm_fault_active", "alert aggregate "+source); err != nil {
			return err
		}
	}
	metrics, err := state.allMetrics()
	if err != nil {
		return err
	}
	for _, metric := range metrics {
		stateKey := metricStateKey(metric)
		if err := add("sensor", stateKey, "metric "+stateKey); err != nil {
			return err
		}
		if isAlertMetric(metric) {
			if err := add("binary_sensor", stateKey+"_active", "alert metric "+stateKey); err != nil {
				return err
			}
		}
	}
	return nil
}

func validateDiscoveryBinding(binding discoveryStateBinding) error {
	values := []struct {
		name  string
		value string
		limit int
	}{
		{name: "topic prefix", value: binding.TopicPrefix, limit: maxDiscoveryStateTopic},
		{name: "discovery prefix", value: binding.DiscoveryPrefix, limit: maxDiscoveryStateTopic},
		{name: "device ID", value: binding.DeviceID, limit: maxDiscoveryStateShortText},
		{name: "device identifier", value: binding.DeviceIdentifier, limit: maxDiscoveryStateShortText},
		{name: "state topic", value: binding.StateTopic, limit: maxDiscoveryStateTopic},
		{name: "availability topic", value: binding.AvailabilityTopic, limit: maxDiscoveryStateTopic},
		{name: "primary source", value: binding.PrimarySource, limit: maxDiscoveryStateShortText},
	}
	for _, item := range values {
		if item.value == "" || len(item.value) > item.limit {
			return fmt.Errorf("MQTT discovery state binding %s is empty or too long", item.name)
		}
	}
	if binding.DeviceID != sanitizeID(binding.DeviceID) {
		return errors.New("MQTT discovery state binding device ID is not normalized")
	}
	if normalized, err := config.NormalizeMQTTTopicPrefix(binding.TopicPrefix); err != nil || normalized != binding.TopicPrefix {
		return errors.New("MQTT discovery state binding topic prefix is not normalized")
	}
	if normalized, err := config.NormalizeMQTTTopicPrefix(binding.DiscoveryPrefix); err != nil || normalized != binding.DiscoveryPrefix {
		return errors.New("MQTT discovery state binding discovery prefix is not normalized")
	}
	if binding.DeviceIdentifier != "jinko_exporter_"+binding.DeviceID {
		return errors.New("MQTT discovery state binding device identifier is invalid")
	}
	if binding.StateTopic != binding.TopicPrefix+"/"+binding.DeviceID+"/state" {
		return errors.New("MQTT discovery state binding state topic is invalid")
	}
	if binding.AvailabilityTopic != binding.TopicPrefix+"/availability" {
		return errors.New("MQTT discovery state binding availability topic is invalid")
	}
	if binding.PrimarySource != normalizeSourceName(binding.PrimarySource) {
		return errors.New("MQTT discovery state binding primary source is not normalized")
	}
	return nil
}

func validateMetricSchemas(category string, schemas map[string]discoveryMetricSchema, accepts func(model.Metric) bool) error {
	if schemas == nil {
		return fmt.Errorf("MQTT discovery state %s metric schemas must not be null", category)
	}
	for stateKey, schema := range schemas {
		metric := schema.metric()
		if stateKey == "" || stateKey != metricStateKey(metric) || len(stateKey) > maxDiscoveryStateMetricName {
			return fmt.Errorf("MQTT discovery state %s metric key %q does not match its schema", category, stateKey)
		}
		if (schema.Key == "" && schema.Name == "") || len(schema.Group) > maxDiscoveryStateShortText || len(schema.Key) > maxDiscoveryStateShortText || len(schema.Name) > maxDiscoveryStateMetricName || len(schema.Unit) > maxDiscoveryStateShortText {
			return fmt.Errorf("MQTT discovery state %s metric %q contains empty or oversized fields", category, stateKey)
		}
		if !accepts(metric) {
			return fmt.Errorf("MQTT discovery state metric %q is stored in the wrong %s category", stateKey, category)
		}
	}
	return nil
}

func alertDomain(source string) string {
	if strings.TrimSpace(source) == "" {
		return "unknown_source"
	}
	domain := sanitizeID(source)
	if domain == "" {
		return "unknown_source"
	}
	return domain
}
